### ISSUE TITLE
RawFilePath instead of FilePath

### ISSUE THREAD

**Issue by BardurArantsson** [tensor5/linux-xattr#1]
Since we now (since unix >= 2.6.0, I believe) have System.Posix.ByteString with RawFilePath (aka. ByteString) would it be possible to support giving the file path directly as a raw ByteString instead of needlessly going through a String?

**Comment by tensor5** [comment]
It sounds reasonable: there should be a module called `System.Linux.XAttr.ByteString` which uses `ByteString`'s instead of `FilePath`'s, like it's done in `unix`.
I would prefer using `ByteString` directly though, rather than the type synonym `RawFilePath`, so that I don't have to add the dependency on `unix >= 2.6`.

Patches are always welcome!
